### ISSUE TITLE
Remove "Serverless" icon for "Kabanero Collections" on Home Page

### ISSUE THREAD

**Issue by bschrammIBM** [kabanero-io/kabanero-website#112]
#### Feature description
There are 4 buttons for "Kabanero Collections" on the Home Page. The "Serverless" button needs to be removed. Serverless is an optional deployment method that can be applied to any collection, it is not a collection.

Also the buttons should be updated to reflect the Collections for MVP, per @ralanlittle .
We can have separate buttons for each NodeJS and Spring collection, or one button that displays the different options.
They are: 
1 - Microprofile OpenLiberty.io/docs
2 - NodeJS
NodeJS
NodeJS Express
NodeJS LoopBack
3 - SpringBoot https://spring.io/guides
Spring on OpenLiberty
Spring on Tomcat
#### Additional context

**Comment by alohr51** [comment]
@nateziemann does this sound good to you?

**Comment by nateziemann** [comment]
I'm fine w/ above.  A couple comments:  I heard rumors on removing the Springboot with OpenLiberty and only having the Springboot with Tomcat.  Check w/ Alan Little on that.  Removal of the "Serverless" one is a necessity and we do need to figure out how to advertise that all collections can be deployed on Kuberentes or Serverless using Knative serving.
