### ISSUE TITLE
Inclusion of Google reCAPTCHA in slackin invite to prevent abuse

### ISSUE THREAD

**Issue by SueChaplain** [kabanero-io/kabanero-website#116]
Suggestion:

Slackin is vulnerable to abuse (see https://github.com/rauchg/slackin/issues/137). Adding reCAPTCHA prevents unwanted spam.

Also suggest that "Request an invite to the channel" opens in a new window (target="_blank")

**Comment by alohr51** [comment]
@SueChaplain Thanks for the suggestion. Looks like slackin has support for Google reCAPTCHA. It seems like it would be up to the owners of https://slack-invite-ibm-cloud-tech.mybluemix.net/ to enable that feature.

 The slack invitation link def should open in a new tab, thanks!

**Comment by SueChaplain** [comment]
@alohr51 @kidus60 

I don't think this issue should be closed completely. Opening in a new tab is fixed but reCAPTCHA is not implemented .... or is that work being handled in an issue elsewhere?

**Comment by alohr51** [comment]
@SueChaplain In my comment above I mentioned it needs to be handled by the team that uses Slackin. Its not part of this website. We need to figure out how to get in contact with the owners of https://slack-invite-ibm-cloud-tech.mybluemix.net/

**Comment by SueChaplain** [comment]
@alohr51 OK, I'll invite myself to the slack and ask there. Didn't realise it was a separate team handling.
