### ISSUE TITLE
Kabanero logging and monitoring guides publishing works

### ISSUE THREAD

**Issue by fwji** [kabanero-io/kabanero-website#127]

**Comment by alohr51** [comment]
app monitoring guide is here https://github.com/kabanero-io/guide-app-monitoring

app logging guide is here https://github.com/kabanero-io/guide-app-logging

After we publish the site today we will work on getting these out later this week.

**Comment by mingcyu** [comment]
@alohr51 Is this needed for 0.3 or 0.4?

**Comment by alohr51** [comment]
@mingcyu doesn't matter which version, the website will just publish them when they're ready.

**Comment by alohr51** [comment]
Both guides were published 

app logging is published https://kabanero.io/guides/app-logging/
app monitoring is published https://kabanero.io/guides/app-monitoring/
