### ISSUE TITLE
Get started "developer-tools" is confusing for users

### ISSUE THREAD

**Issue by SueChaplain** [kabanero-io/kabanero-website#158]
I was looking at https://kabanero-kdsee.us-south.cf.test.appdomain.cloud/get-started/, which is a great improvement, design-wise, on the existing Try It! develop experience page.

@mdenby @alohr51 
There are a few inaccuracies / confusing points, that are probably easy to clear up with some re-ordering.

1. Having the Pre-requisites above the tools instructions is confusing. Depending on whether you choose to use an IDE or the Appsody CLI, you don't need them all (At first sight I wonder which ones I need). Perhaps the pre-reqs should be split out and introduced as part of each tool instruction, even if one or two are repeated.

2. Leading sentence "Install Codewind using:" is incorrect. You need codewind only for the IDEs, not Appsody CLI. This should be removed or replaced with a different lead in.

3. Typo on the Visual Studio tab. Visually, I'd be more inclined to call this tab "VS Code", which any developer who uses it and wants to try it that way will be familiar with.

4. Tab "CLI instructions" seems at odds with the other tabs. Perhaps all the tabs should include the word "instructions", or none of them? 

@bschrammIBM 
I presume that the instructions under each option are targeted by issues in the docs repo, like https://github.com/kabanero-io/docs/issues/38 for the CLI?

~I believe the VSCode and Eclipse ones should also mention installing Appsody extensions (unless something changed recently) but I don't see an issues that relate to these.~ Looks like that did change very recently, extensions installed by default when you install codewind. That's a good improvement!

**Comment by alohr51** [comment]
@mdenby looking for your feedback too.

1. I agree the pre requeqs should probably be inside each tabs content and specific to that tab.

2. Yup

3. The typo has been fixed

4. Yeah seems like "instructions" can be removed to make it less oddball in context with the 2 other tabs.

**Comment by mdenby** [comment]
@alohr51 I also agree on 1, 2, 3. 

4.I'm also fine removing the word "instructions".

@SueChaplain Thanks for the feedback! :-)
