### ISSUE TITLE
New "Get started" page: Top box title might be better placed above the box?

### ISSUE THREAD

**Issue by SueChaplain** [kabanero-io/kabanero-website#162]
@mdenby - I was wondering whether it made sense to move the lead in text for the top box outside/above the box, so that it balances with the lead in text for the lower boxes?

![Screenshot 2019-09-11 at 09 19 29 2](https://user-images.githubusercontent.com/18395037/64680617-0bc1f200-d476-11e9-9929-873df2112074.png)

Looks like Andrew already fixed the typo "developement"

**Comment by mdenby** [comment]
Sure--I'm okay with that. Also, we have an awesome, new visual designer that is working on some new things to make the site look better. Hopefully, we'll get to show off some of her work soon!

**Comment by SueChaplain** [comment]
Sounds good @mdenby - is there anyone else that needs to +1 this? If not, @Bazif-Khan can help out and handle this.

**Comment by mdenby** [comment]
@SueChaplain Nope--It should be good to make the change.
