### ISSUE TITLE
Typo in the new getting started page

### ISSUE THREAD

**Issue by bschrammIBM** [kabanero-io/kabanero-website#165]
#### Describe the bug
https://kabanero-kdsee.us-south.cf.test.appdomain.cloud/get-started/
There is a typo in this line:
Use our developement tools to explore Kabanero Public Collections

#### Expected behavior
Use our development tools to explore the Kabanero Public Collections

#### Steps to reproduce the bug
3. Scroll to '....'

#### Environment where the bug occurred 
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [ ] Chrome (Desktop)
- [ ] Internet Explorer (Desktop)
- [ ] iOS (Mobile)
- [ ] Android (Mobile)

**Comment by alohr51** [comment]
this has been fixed in #159
