### ISSUE TITLE
Incomplete section on cli page

### ISSUE THREAD

**Issue by rajivnathan** [kabanero-io/kabanero-website#174]
#### Describe the bug

Just noticed a section that looks incomplete on the kabanero cli page: https://kabanero.io/developer/cli/

- The section says "Point Appsody at your collections" but doesn't explain how.
- The command examples for create a project and deploy seem to be placeholders

#### Screenshots

![image](https://user-images.githubusercontent.com/20015929/64870958-46f92800-d612-11e9-802c-8342e858f73d.png)

**Comment by alohr51** [comment]
@rajivnathan yup that is definitely incomplete. The whole page is redone (which fixes this issue) in a new experience we will be rolling out. It's not released yet. Thanks for reporting it! The new steps that will be sent out can be seen here https://github.com/kabanero-io/kabanero-website/blob/master/src/main/content/developer-tools.html#L174
