### ISSUE TITLE
Docs page should have a fuller overview

### ISSUE THREAD

**Issue by SueChaplain** [kabanero-io/kabanero-website#195]
Although we have a new guide to help user understand the architecture and development flows (https://github.com/kabanero-io/guide-overview), it feels as if we are lacking something in the Docs view. We have a short welcome and then go straight in to "Installation", "Configuration", and "Reference".

Could part of this new guide be repurposed to inform users who head directly to "Docs" rather than the Guides? We ought to open this view with more information about Kabanero, even if we link to the Guide for a tutorial.

**Comment by mingcyu** [comment]
@alohr51 We would like to close this issue to be included in another epic for documentation reorganization
