### ISSUE TITLE
Guides page needs improvements for mobile responsiveness

### ISSUE THREAD

**Issue by SueChaplain** [kabanero-io/kabanero-website#196]
#### Describe the bug

- Mobile view looks good
- Full screen desktop view looks good
- Shrinking the screen causes some box content to spill outside the boxes.

#### Expected behavior

Content stays within guide boxes at all display sizes.

#### Actual behavior

![responsiveissue](https://user-images.githubusercontent.com/18395037/65063204-ac804800-d975-11e9-8f5b-a196c8de5586.png)

#### Steps to reproduce the bug
1. Go to https://kabanero.io/guides/
2. Grab the corner of the screen and shrink horizontally

#### Environment where the bug occurred 
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [x] Chrome (Desktop)
- [ ] Internet Explorer (Desktop)
- [ ] iOS (Mobile)
- [ ] Android (Mobile)

#### Additional context

Only tested on Chrome. Likely an issue on all browsers

**Comment by SueChaplain** [comment]
@Bazif-Khan could probably help here if others are not already working on this.

**Comment by alohr51** [comment]
Sounds good, I'll assign @Bazif-Khan, Bazif let me know if you would like to be unassigned
