### ISSUE TITLE
Need a contribution page that is linked to from the bottom of the main page

### ISSUE THREAD

**Issue by ralanlittle** [kabanero-io/kabanero-website#2]
We need a contribution page that is linked to from the bottom of the main page.

**Comment by marikaj123** [comment]
For the Kabanero CLA document, I am adding this here, in case the team may want to use it as a reference sample doc:  https://github.com/OpenLiberty/open-liberty/blob/master/CONTRIBUTING.md#contributor-license-agreement
FYI: For Open Liberty,  when a PR is created the GH web hooks check the PR owner with their DB and if an IBMr - and set the appropriate labels, eg: ‘CLA assigned’.

**Comment by marikaj123** [comment]
Will deliver by May 7.
Page points to contribution.md.
