### ISSUE TITLE
Not getting access to Kabanero Public slack

### ISSUE THREAD

**Issue by aadeshpa** [kabanero-io/kabanero-website#213]
#### Describe the bug
I tried clicking the slack on website https://kabanero.io/ and it asks me to login to slack with emailid and password.
I entered my w3id and password and it does not allow me to go to the slack channel.

Attaching the screenshot

#### Steps to reproduce the bug
3. Scroll to '....'

#### Environment where the bug occurred 
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [ ] Chrome (Desktop)
- [ ] Internet Explorer (Desktop)
- [ ] iOS (Mobile)
- [ ] Android (Mobile)

**Comment by aadeshpa** [comment]
<img width="1394" alt="Screen Shot 2019-09-23 at 11 05 23 AM" src="https://user-images.githubusercontent.com/53223993/65437682-3a36ba00-ddf2-11e9-971f-9a5b4367c2a0.png">

**Comment by tseelbach** [comment]
The next screen says to contact your workspace admin but does not say who that is.

**Comment by alohr51** [comment]
if you scroll down on kabanero.io you will see a link to “Request an invite to the channel.” which you need to do first. 

We probably can put that invite link in a better place so users know to do that first.

**Comment by alohr51** [comment]
@mdenby any ideas on how we can make that invite link better placed?

**Comment by aadeshpa** [comment]
Requested the invite as per the link : https://slack-invite-ibm-cloud-tech.mybluemix.net/
Will wait and see if I get any invite.

**Comment by alohr51** [comment]
We'll go with a drop down when you click the slack icon where it will have 2 options 1 to request invite and 1 to go to the channel. This way is more clear you should request an invite first
