### ISSUE TITLE
Footer Desktop view

### ISSUE THREAD

**Issue by Bazif-Khan** [kabanero-io/kabanero-website#218]
#### Describe the bug
There should be some margin on the left side of Kabanero logo in the footer. On the right side of social media icons space should be reduced.

#### Screenshots
![image](https://user-images.githubusercontent.com/51790085/65442658-7c78ef00-de24-11e9-807f-a427648af424.png)

**Comment by Bazif-Khan** [comment]
@alohr51 can I start the work on this? if others are not already working on this.

**Comment by alohr51** [comment]
@Bazif-Khan yup go for it, thanks
