### ISSUE TITLE
add info about multiple namespace support to website

### ISSUE THREAD

**Issue by tseelbach** [kabanero-io/kabanero-website#224]
update website to say that Kabanero supports multiple namespaces

**Comment by mingcyu** [comment]
@alohr51 @tseelbach

Does this document satisfy this issue  https://kabanero.io/docs/ref/general/configuration/app-deploy-namespace.html

?

**Comment by alohr51** [comment]
sounds okay to me, up to Tom if this can be closed.

**Comment by mingcyu** [comment]
@tseelbach Can you confirm if the link above satisfies this issue?

**Comment by kabynarow** [comment]
Yes - looks good! Can be closed.  Thanks @mingcyu and @alohr51

**Comment by mingcyu** [comment]
@alohr51 Can you go ahead and close this issue?  Neither Tom or I have ability to close it out
