### ISSUE TITLE
NLS Translate the Kabanero.io main site text

### ISSUE THREAD

**Issue by alohr51** [kabanero-io/kabanero-website#23]
We can use Jekyll to handle translated files (using a plugin) one that comes in searches that looks good is https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin

We will probably have translated files in different languages and just deciding which text to show on the site will be the plugins job.

**Comment by kidus60** [comment]
pr to close this issue out --- https://github.com/kabanero-io/kabanero-website/pull/118
