### ISSUE TITLE
Introduce kAppNav in kabanero.io

### ISSUE THREAD

**Issue by alohr51** [kabanero-io/kabanero-website#231]
Spawning from https://github.com/kabanero-io/kabanero-operator/issues/116#issuecomment-535068289 we need some content (and logo) that introduces kappnav and links to https://kappnav.io

**Comment by marikaj123** [comment]
@mdenby and @alohr51 this issue is a child of the Epic targeted for v0.2 Kabanero release; as a result, labelled it with release-0.2.

**Comment by marikaj123** [comment]
Chris is planning to propose content based on the current kabanero.io website.

**Comment by cvignola** [comment]
After reviewing kabaner.io thoroughly,  kAppNav mentions make sense in the following locations: 

1. guides 
2. main page/operations tab 
3. Try it/Todd experience 

I recommend the following actions: 

1. a kAppNav guide is [in the works](https://github.com/kabanero-io/docs/issues/57)
2. main page/operations tab needs no update
3. a small update to [Try it/Todd experience](https://kabanero.io/operations/) would make sense

**Comment by cvignola** [comment]
Referring back to the [previous comment](https://github.com/kabanero-io/kabanero-website/issues/231#issuecomment-543295067),  the main page/operations tab says the following: 

![image](https://user-images.githubusercontent.com/15363082/67035523-6e468780-f0df-11e9-970f-634e3d290a77.png)

The last sentence is an allusion to kAppNav without calling out the technology by name.  The paragraph is high level and mentions no technologies whatsoever.   So I think no change is necessary here.

**Comment by cvignola** [comment]
Referring back to the [comment before last](https://github.com/kabanero-io/kabanero-website/issues/231#issuecomment-543295067),  the [Try it/Todd experience](https://kabanero.io/operations/) says the following: 

![image](https://user-images.githubusercontent.com/15363082/67035794-f593fb00-f0df-11e9-95fc-f51175a96e42.png)

------------------------------
Since this page talks about Applications in the context of Todd's experience, I believe it would be appropriate to say something about application day 2 operations and kAppNav.  

I propose the following addition to https://kabanero.io/operations/ : 

The optional [Kubernetes Application Navigator (kAppNav)](https://kappnav.io/) technology provides application visibility and enables day 2 operations. 

@alohr51 @barecode

**Comment by cvignola** [comment]
@alohr51 Hey, sorry, I missed an update to this page:  https://kabanero.io/operations/kabanero-foundation-install/    It shows this: 

![image](https://user-images.githubusercontent.com/15363082/67043276-5aa31d00-f0ef-11e9-9b1e-d1826b5b57d0.png)

------------
The preceding states:  "Kabanero Foundation installs the foundational open technologies (Knative, Istio, Tekton), ..."

It would be good to add kAppNav to that parethentical - i.e. (Knative, Istio, Tekton, kAppNav)

**Comment by cvignola** [comment]
@alohr51 OK ...  hopefully last one :) 

I haven't installed Kabanero personally - until now.   What I _thought_ was an interactive prompt to install the optional kAppNav component, is in fact an environment variable.   

So ....   we need to inform the user how to install this optional component.  It is controlled by the ENABLE_KAPPNAV environment variable.

We need the change on this page:  https://kabanero.io/docs/ref/general/installing-kabanero-foundation.html

It looks like this:  

![image](https://user-images.githubusercontent.com/15363082/67060619-424cf580-f123-11e9-8d18-40d39cebb736.png)

I propose we modify step 5 to say the following: 

5. As a cluster-admin, run the following:

   o Don’t forget to replace <MY_OPENSHIFT_MASTER_DEFAULT_SUBDOMAIN> with your subdomain, and do not include the angle brackets:

     o Decide whether or not to install the optional [kAppNav](https://kappnav.io/) component by specifying 'yes' or 'no' on the ENABLE_KAPPNAV environment variable.  

     o  ENABLE_KAPPNAV=yes|no openshift_master_default_subdomain=<MY_OPENSHIFT_MASTER_DEFAULT_SUBDOMAIN> ./install-kabanero-foundation.sh

**Comment by jantley-ibm** [comment]
@alohr I can handle the doc change to  https://kabanero.io/docs/ref/general/installing-kabanero-foundation.html

**Comment by jantley-ibm** [comment]
@cvignola I couldn't add you as a reviewer to the PR, but here it is in case you want to look it:
https://github.com/kabanero-io/docs/pull/146
