### ISSUE TITLE
Have Appsody Download Link Point to Appsody Docs

### ISSUE THREAD

**Issue by Jhschube** [kabanero-io/kabanero-website#24]
In the new download tab on the website, there is existing docs on the Appsody website that can be pointed to instead of replicating the docs internally. 
Here is a link to the download/install instructions: https://appsody.dev/docs/getting-started/installation

**Comment by marikaj123** [comment]
Assignee: Melissa

**Comment by alohr51** [comment]
This is done, we link to the Appsody installation in Jane's CLI experience page https://kabanero.io/developer/cli/
