### ISSUE TITLE
Create a RELEASE.md file that explains the website, doc, guides, and blogs release process'

### ISSUE THREAD

**Issue by alohr51** [kabanero-io/kabanero-website#244]
#### Feature description

We need to write down the release process for our website, docs, guides, and blogs. Also what needs to happen if a hot fix needs to go into a current release.

# Website Release

The website is on its own release process. _add more explaining_

# Guides Release

Put this info in the draft-guide-template repo
There are no "releases" for guides just the removal of draft- gets them published on next website publish

# Blogs Release

on its own release process. For new blogs we will bump the **Minor** version and use the latest release when the website is published

# Docs Release

This is the release process for Kabanero as a whole - Kabanero uses [semver](https://semver.org/) versioning. The docs repo will follow this same process.

Here is an example flow of the Kabnero release using `0.2.0` as the next release example:

**Assumption**: When a new release of Kabanero as a whole is ready the next version number will always be a **Major** or **Minor** bump (never a **Patch** bump).

1. When 0.2.0 release date comes we cut the 0.2.0 release on the repo. End of release process.

## Docs repo needs a hot fix for 0.2.0 example

1. If after a release, A piece of Kabanero (cli, pipelines, operator, docs, etc...) needs to do a small update or a quick bug fix or something (and should be deployed before the next scheduled release, 0.3.0, in this example) we would:
1. create a `release-0.2` branch based off the 0.2.0 release. 
1. Put the changes in the `release-0.2` branch and `master` branch, if applicable (see Note below).
1. Cut a new release based off the `release-0.2` branch and bump the patch number so it becomes `0.2.1`
1. Publish release `0.2.1`.

**Note**: During this whole hox fit situation the `master` branch will always be going towards the next release so new stuff in master will always be `0.3.0` related.

**Comment by marikaj123** [comment]
@alohr51 - Is the content ready for Alan/Nate to review? If yes, please make them as reviewers to the PR.  Thank you.

**Comment by alohr51** [comment]
Actually @garypicher would be a better person to review this content. I'll ask him if he can

**Comment by marikaj123** [comment]
@alohr51 - Looking at Create RELEASE.md kabanero-io/draft-guides-template#3 - seems it is ready for publishing.
https://github.com/kabanero-io/kabanero-website/pull/245 --> How can we get it approved and merged?
https://github.com/kabanero-io/docs/pull/113 --> How can we get it approved and merged?
