### ISSUE TITLE
Font styles for guide headers are indistiguishable from regular text

### ISSUE THREAD

**Issue by nastacio** [kabanero-io/kabanero-website#248]
#### Describe the bug
Header level 3 and higher use a font weight and size that makes it either indistinguishable (level 3) or less visible (level 4) than regular text.

#### Expected behavior
Header level 3 should offer some level of visual highlight over regular text, such as a larger font-size or, if using the same font-size as regular text, a heavier weight.

#### Actual behavior
Header level 3 has the exact same font-size and weight as regular text, making it indistinguishable from regular text. Some guides have worked around the issue by manually adding bold style (using the + character in the asciidoc content) , which then introduces the side-effect of also making the text bold in the table of contents.

See screenshots below for examples of defect and side-effect in workaround.

#### Steps to reproduce the bug
1. Launch this guide "https://kabanero.io/guides/collection-microprofile" and visually inspect the styling of the header "Understanding the project layout" both in the text and in the contents table

#### Environment where the bug occurred 
- [x] Firefox (Desktop)
- [ ] Safari (Desktop)
- [x] Chrome (Desktop)
- [ ] Internet Explorer (Desktop)
- [ ] iOS (Mobile)
- [ ] Android (Mobile)

#### Screenshots
Without the workaround:
![kabanero-guide-style-level3-same-as-text](https://user-images.githubusercontent.com/3278623/66155406-8d2c2080-e5ed-11e9-83c5-a4f37e9438d2.png)

With the workaround, side-effect in contents bar:
![kabanero-guide-style](https://user-images.githubusercontent.com/3278623/66155301-5229ed00-e5ed-11e9-8355-7cc436d31731.png)

#### Additional context

None

**Comment by nastacio** [comment]
cc @alohr51

**Comment by SueChaplain** [comment]
@alohr51 - @KyeMaloy97 is looking at this. Do you want to assign him?

**Comment by KyeMaloy97** [comment]
Opened PR #282 to resolve this issue.
