### ISSUE TITLE
"Git clone to get going" message for guides that don't need cloning

### ISSUE THREAD

**Issue by nastacio** [kabanero-io/kabanero-website#278]
#### Describe the bug
Whenever I shrink the screen horizontally past a certain point, I see the message 

You can see that behavior, for instance, in https://kabanero.io/guides/collection-microprofile/

#### Expected behavior
There is nothing to be cloned while reading the guide. I don't want it to be displayed.

#### Actual behavior
The instruction is displayed to the user, even though not mentioned in or required by the steps in the guide.

#### Steps to reproduce the bug
1. Go to any guide, e.g. https://kabanero.io/guides/collection-microprofile/
![git-clone-instruction](https://user-images.githubusercontent.com/3278623/67820653-88457a00-fa90-11e9-8584-457be445e210.png)

2. Shrink the window horizontally until the message is displayed
3. See error

#### Environment where the bug occurred 
- [x] Firefox (Desktop)
- [x] Safari (Desktop)
- [x] Chrome (Desktop)
- [ ] Internet Explorer (Desktop) - Not tested
- [ ] iOS (Mobile) - Not tested 
- [ ] Android (Mobile) - Not tested

#### Additional context
None
![git-clone-instruction](https://user-images.githubusercontent.com/3278623/67820663-909db500-fa90-11e9-96a5-929546157d32.png)

**Comment by nastacio** [comment]
cc @alohr51 , @kSee04

**Comment by KyeMaloy97** [comment]
I'm going to look into the issue, however I need some idea of the purpose of the box. Given the link it displays, its meant to offer a quick guide to editing the actual guides content, not any developer-y.

Therefore, if we are encouraging people to contribute, we should show the guide all the time, whether on mobile or desktop (but maybe make it clearer that the box is showing a link to update the docs, not anything else).

By removing the box, we wouldn't be losing anything other than the ability to fast track people who want to make a tweak to the guide. Before I start working on the problem, can I get clarification on what route we want to go down? @alohr51 @SueChaplain

**Comment by nastacio** [comment]
@KyeMaloy97 , the purpose of "offer a quick guide to editing" is met with the "What could make this guide better?" section at the very bottom of the guide:

```
What could make this guide better?
Raise an issue to share feedback
Create a pull request to contribute to this guide
```

This clone instruction at the top is, in my opinion, useful for guide repos containing source code that will be referenced and used through the guide, such as "Copy the file XYZ from the cloned repo to the directory ABC in the local machne."

**Comment by alohr51** [comment]
Yeah I agree with @nastacio OL had guides that wanted you to follow along on your laptop and run stuff there so it was a quick way to get the code pulled down.

I don't think any of our guides do that (so far) and in the future we can just put a clone command in the guide itself. Managing this .js that does this seems like it will be burdensome. I would vote to remove that pop up and if we need that feature, then just put a clone command directly in the guide.

**Comment by KyeMaloy97** [comment]
Opened a PR #285 to address this issue.
