### ISSUE TITLE
Integrate the CLA assistant to streamline PR requests

### ISSUE THREAD

**Issue by KyeMaloy97** [kabanero-io/kabanero-website#283]
#### Feature description
Appsody, along with some other IBM properties use a tool provided by SAP called the CLA Assistant to administrate the signing of the CLA. It acts as a check when a PR is open and offers a simple one time click for a contributor, and allows admins to see who's signed and who has not. It also ensures we are following the required steps for open source contributions. 

#### Additional context
It is relatively simple to set up, it just needs turning on for the repo and a CLA being uploaded to the service.

**Comment by KyeMaloy97** [comment]
@alohr51 - as I cannot assign people to the issue haha, what are your thoughts on using this system?

**Comment by dianak2016** [comment]
Note we have an epic for this already: https://github.com/kabanero-io/roadmap/issues/55

**Comment by alohr51** [comment]
thanks @dianak2016. @KyeMaloy97 going to close this as a dup, for to keep up with the signed cla process work you can reference the above epic
