### ISSUE TITLE
Using old Slack logo

### ISSUE THREAD

**Issue by DunnCoding** [kabanero-io/kabanero-website#287]
I've noticed that throughout the Kabanero site the old Slack logo is being using. Slack updated their logo at the start of this year so I'm not sure how the old one made it in but we should update all instances of the logo to the correct logo for Slack.

**Comment by alohr51** [comment]
@mdenby whenever you have time - it looks like the website could use an updated slack logo.

**Comment by alohr51** [comment]
Updated logo asset here:

[Slack-selected-assets.zip](https://github.com/kabanero-io/kabanero-website/files/3825287/Slack-selected-assets.zip)
