### ISSUE TITLE
Broken link on PV setup

### ISSUE THREAD

**Issue by gecock** [kabanero-io/kabanero-website#300]
#### Describe the bug
There is a broken link on this page -- https://kabanero.io/docs/ref/general/tekton-webhooks.html for [Creating a persistent volume](https://github.com/kabanero-io/kabanero-pipelines/tree/Readme-updates#create-a-persistent-volume)

#### Expected behavior
I get linked out to the persistent volume page

#### Actual behavior
404 error

#### Steps to reproduce the bug
1. Go to https://kabanero.io/docs/ref/general/tekton-webhooks.html
2. Click on [Creating a persistent volume](https://github.com/kabanero-io/kabanero-pipelines/tree/Readme-updates#create-a-persistent-volume)

#### Environment where the bug occurred 
- [x] Firefox (Desktop)
- [ ] Safari (Desktop)
- [ ] Chrome (Desktop)
- [ ] Internet Explorer (Desktop)
- [ ] iOS (Mobile)
- [ ] Android (Mobile)

**Comment by jantley-ibm** [comment]
Issue moved to [kabanero-io/docs #234](https://github.com/kabanero-io/docs/issues/234) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jantley-ibm** [comment]
@gecock the newly created issue 234 in docs repo was closed as a dupe but I don't have permission to close this.  I thought it would automatically close when I moved it.  Fix being handled in https://github.com/kabanero-io/docs/issues/220

**Comment by gecock** [comment]
Sounds good thanks for the heads up. I'll close this then
