### ISSUE TITLE
Install kabanero in OCP 4

### ISSUE THREAD

**Issue by DanielChuDC** [kabanero-io/kabanero-website#312]
#### Describe the bug
Installation guide in https://kabanero.io/docs/ref/general/installing-kabanero-foundation.html under `Manual installation` step 7 and 8, The `che operator` and `kabanero operator` both cannot find in the OCP 4.2 cluster in community market place or [Operator Hub](https://operatorhub.io/)

#### Expected behavior
I am able to follow the instruction to install it.

#### Actual behavior
The `che operator` and `kabanero operator` both cannot find in the OCP 4.2 cluster in community market place or [Operator Hub](https://operatorhub.io/)

#### Steps to reproduce the bug
1. Go to  'https://kabanero.io/docs/ref/general/installing-kabanero-foundation.html '
2. Navigate to Manual Installation section
3. Scroll to 'step 7 and 8'

#### Environment where the bug occurred 
OCP cluster 4.2.10

#### Additional context
<img width="1526" alt="Screenshot 2019-12-09 at 3 20 59 PM" src="https://user-images.githubusercontent.com/52316624/70415478-ab077d00-1a97-11ea-9e51-91afb883d7e0.png">
<img width="1453" alt="Screenshot 2019-12-09 at 3 21 16 PM" src="https://user-images.githubusercontent.com/52316624/70415479-aba01380-1a97-11ea-8f04-a8c7d62a2c92.png">

**Comment by alohr51** [comment]
@DanielChuDC The linked doc titled [Installing Operators from the OperatorHub](https://docs.openshift.com/container-platform/4.2/operators/olm-adding-operators-to-cluster.html#olm-installing-from-operatorhub-using-web-console_olm-adding-operators-to-a-cluster) mentions you should use the catalog inside the web console. Inside your OCP 4.2 console you should navigate to **Operators -> Operator Hub** and search for the operator you want to install there.

Let me know if this helps or not. I bet we can improve the docs with your help.

Note: I would suggest using the [Scripted Installation](https://kabanero.io/docs/ref/general/installation/installing-kabanero-foundation.html#scripted-installation) if possible.

![image](https://user-images.githubusercontent.com/3623618/70453337-94046300-1a76-11ea-96b9-4d4256060941.png)

**Comment by DanielChuDC** [comment]
Yup! Thank you for your reply.

I am willing to help to improve the doc!

Btw, I did try out the scripts installation and it went smoothly.

From the scripted installation then I realised the 'che operator' is 'eclipse che operator'.

But the 'kabanero operator's still cannot find in the catalog but I saw the script installation pull successfully.

Hope can get explain on what it happens on it.

**Comment by alohr51** [comment]
@DanielChuDC I'm glad the scripted installation went smoothly for you. Can you expand on your question about "'kabanero operator's still cannot find in the catalog"? Are you talking about a specific log you saw or some part of the OCP UI?

**Comment by DanielChuDC** [comment]
So the scenario like this:

I have OCP 4.2 cluster an I try install kabanero and I follow instruction on https://kabanero.io/docs/ref/general/installation/installing-kabanero-foundation.html and not sure step 5 how to proceed. 
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/52316624/70638830-7e5c8c80-1c74-11ea-9441-a40e88cf35ac.png">


Since I never do step 5, I cannot find on the web console.

Later, I try using script installation, and all done! Now, I can use web console to find

<img width="774" alt="image" src="https://user-images.githubusercontent.com/52316624/70639226-25412880-1c75-11ea-9caa-b95e12d949be.png">
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/52316624/70639245-2d00cd00-1c75-11ea-91d0-70a16ce28a7e.png">

---

So I went back the script to check, and realized the script have create more resource than the step 5. I just want to see what we can improve the doc in step 5 👍 in manual creation and asking why the web console will appear 2 appsody operator when searching.

---

**Comment by DanielChuDC** [comment]
Btw, the link in https://kabanero.io/docs/ref/general/installation/installing-kabanero-foundation.html under `Scripted installation section`, `point 4` , the link to  `Kabanero CR configuration reference` is invalid.

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/52316624/70640096-64bc4480-1c76-11ea-99bc-efec0201e3b0.png">

**Comment by alohr51** [comment]
ah okay I got it, Thanks @DanielChuDC. Since this is now morphed into a doc clarification issue, would you mind opening a new issue in our docs repo https://github.com/kabanero-io/docs/issues with your comments in https://github.com/kabanero-io/kabanero-website/issues/312#issuecomment-564623881

I also fixed that link, thanks for mentioning that.

**Comment by DanielChuDC** [comment]
ok closing this issue and open new issue
