### ISSUE TITLE
Install Kabanero foundation page returns a 404

### ISSUE THREAD

**Issue by dinogun** [kabanero-io/kabanero-website#313]
#### Describe the bug
Clicking on "Follow the instructions to install Kabanero Foundation." from the [page](https://kabanero.io/operations/kabanero-foundation-install/) leads to https://kabanero.io/docs/ref/general/installing-kabanero-foundation.html which is a 404 at this time

#### Environment where the bug occurred 
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [x] Chrome (Desktop)
- [ ] Internet Explorer (Desktop)
- [ ] iOS (Mobile)
- [ ] Android (Mobile)

**Comment by alohr51** [comment]
thanks for the heads up @dinogun !
