### ISSUE TITLE
Regression: Table of contents appears in footer, mobile responsive error

### ISSUE THREAD

**Issue by SueChaplain** [kabanero-io/kabanero-website#337]
#### Describe the bug
Regression of https://github.com/kabanero-io/kabanero-website/issues/290 and related to https://github.com/kabanero-io/kabanero-website/issues/288

TOC is OK in a large window, but mobile responsiveness breaks as you shrink the screen until it is small enough for the central Menu to appear

#### Expected behavior

TOC appears as a side-panel until screen width

#### Steps to reproduce the bug

Stage PR: https://github.com/kabanero-io/guide-collection-nodejs-express/pull/14
This is an update to the existing node-js guide in markdown format.

#### Environment where the bug occurred 
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [ x] Chrome (Desktop)
- [ ] Internet Explorer (Desktop)
- [ ] iOS (Mobile)
- [ ] Android (Mobile)

**Comment by alohr51** [comment]
@SueChaplain can you add a screen shot?

**Comment by SueChaplain** [comment]
![toc_issue](https://user-images.githubusercontent.com/18395037/73271901-58198e80-41d9-11ea-95d2-24e1ca00273e.png)

**Comment by alohr51** [comment]
@SueChaplain do you see the same problem on the website? https://kabanero.io/guides/collection-nodejs-express

**Comment by SueChaplain** [comment]
No, but the production doc is in asciidoc source. The new guide is in markdown .... assume there are some differences applied via css? https://github.com/kabanero-io/kabanero-website/issues/290 was reporting the issue in markdown and I am sure it was fixed.

**Comment by kidus60** [comment]
@SueChaplain I tried recreating the issue locally but was unable to do so, can you possibly tell me how I would go about reproducing this issue?

**Comment by SueChaplain** [comment]
Hi @kidus60 

- I build a local website environment in a container, using the process here (https://github.com/kabanero-io/kabanero-website/blob/master/CONTRIBUTING.md) and the dockerfile-dev image. 
- With the most recent pull of the website, I put the https://kabanero-io/guide-collection-nodejs-express#14 files in the kabanero-website/src/main/content/guides/guide-collection-nodejs folder and view localhost:4000.
- Open the guide in Chrome on my desktop in a large window - TOC is on the left hand side as expected.
- Scroll to the footer, then grab the window and start to shrink it.
- At a certain width the TOC moves into the footer in an opaque fashion.
- Keep shrinking and the TOC footer disappears and is replaced with the mobile responsive TOC menu at the top.

I can reproduce this problem in Firefox and in Safari

**Comment by marikaj123** [comment]
According to @kidus60 - the PR contains the fix now is just waiting for a merged.
