### ISSUE TITLE
Incorrect header when site unfurls content from kabanero.io

### ISSUE THREAD

**Issue by dewan-ahmed** [kabanero-io/kabanero-website#340]
#### Describe the bug

When a blog is shared on an external social media site (e.g. LinkedIn), kabanero.io website's "i" tag is attached to the content metadata and shown as the content title.

#### Expected behavior

Text within "i" tag is not shown when sharing content.

#### Actual behavior
<img width="542" alt="Screen Shot 2020-02-04 at 2 04 47 PM" src="https://user-images.githubusercontent.com/30604461/73778585-74797600-4759-11ea-88ad-247a605fe9dc.png">

When a blog is shared on an external social media site (e.g. LinkedIn), kabanero.io website's "i" tag is attached to the content metadata and shown as the content title.

#### Steps to reproduce the bug
3. Scroll to '....'

#### Environment where the bug occurred 
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [ ] Chrome (Desktop)
- [ ] Internet Explorer (Desktop)
- [ ] iOS (Mobile)
- [ ] Android (Mobile)

**Comment by alohr51** [comment]
we might need to add og meta data for linkedin to properly display the content.

We can either add them manually http://davidensinger.com/2013/04/adding-open-graph-tags-to-jekyll/

Or this plugin can help https://github.com/jekyll/jekyll-seo-tag
