### ISSUE TITLE
Kabanero.io website SSL Certificate Expired

### ISSUE THREAD

**Issue by mukeshkmr776** [kabanero-io/kabanero-website#374]
#### Describe the bug
Kabanero.io website SSL Certificate Expired
This SSL certificate for kabanero website has expired.

#### Expected behavior
SSL Certificate always need to be valid.

#### Actual behavior
SSL Certificate expired.

#### Steps to reproduce the bug
1. Go to website https://kabanero.io/
2. Click on 'Not Secure' text before website name in AddressBar
3. Click on certificate
4. Then you will see the date validity which is past now.

#### Environment where the bug occurred 
- [x] Firefox (Desktop)
- [x] Safari (Desktop)
- [x] Chrome (Desktop)
- [x] Internet Explorer (Desktop)
- [x] iOS (Mobile)
- [x] Android (Mobile)

#### Screenshots
![kabanero-2](https://user-images.githubusercontent.com/18456767/82074279-28df4c80-96f8-11ea-88df-d1ab2d1f272d.PNG)

![kabanero-1](https://user-images.githubusercontent.com/18456767/82074285-2aa91000-96f8-11ea-96d0-68121b68477a.PNG)

#### Additional context
NA

**Comment by alohr51** [comment]
Thanks for opening an issue, we're currently working on renewing it

**Comment by alohr51** [comment]
cert is renewed
