### ISSUE TITLE
Change the term stack or application stack to Kabanero Collection

### ISSUE THREAD

**Issue by ralanlittle** [kabanero-io/kabanero-website#38]
![3](https://user-images.githubusercontent.com/5471755/61143055-32c46d80-a49f-11e9-9acc-b0024d8c9262.png)

Change the work stack or application stack to Kabanero Collection at the locations I circled on the screen shot

**Comment by kSee04** [comment]
@ralanlittle the `Application Stacks` section was removed in https://github.com/kabanero-io/kabanero-website/pull/32.  I updated the one remaining instance of `stack` on the home page in the PR that I linked.
