### ISSUE TITLE
Invalid/Expired SSL Cert

### ISSUE THREAD

**Issue by nathanclayton** [kabanero-io/kabanero-website#381]
#### Describe the bug
The Kabanero website currently has an invalid SSL certificate

#### Expected behavior
Able to navigate to the website without errors

#### Actual behavior
Expired SSL certificate warning is shown

#### Steps to reproduce the bug
1. Go to the Kabanero website (https://kabanero.io)
2. See error

#### Environment where the bug occurred 
- [x] Firefox (Desktop)
- [x] Edge (Desktop)
- [ ] Safari (Desktop)
- [x] Chrome (Desktop)
- [ ] Internet Explorer (Desktop)
- [ ] iOS (Mobile)
- [ ] Android (Mobile)

#### Screenshots
![2021-06-02_11-23-19](https://user-images.githubusercontent.com/44933/120533354-80993600-c395-11eb-92ce-028a1def81a9.jpg)

**Comment by mchenggit** [comment]
Changed to html only site at http://kabanero.io.  (Note: https://kabanero.io is not available.)
