### ISSUE TITLE
Add new video to the website.

### ISSUE THREAD

**Issue by ralanlittle** [kabanero-io/kabanero-website#39]
Alan will add a new video that we will use for our OSCON annouce too our YOUTUBE Channel and will add the link once it is avaiable (should be this weekend).  The video that is on the site will be replaced.

**Comment by ralanlittle** [comment]
https://www.youtube.com/watch?v=gIrwcneJyBA

Is the new video

**Comment by nateziemann** [comment]
I want this video linked on the Try It page.  Please keep the current video thats on the main homepage as is for now.  We need to replace that one with a voice over video that replaces Chris's in near future.  The video link above is included in the new "Try it" page documented in issue #37

**Comment by alohr51** [comment]
latest try-it page video link https://youtu.be/Ri7RJ5XyY60
