### ISSUE TITLE
The announce blog needs to be added to the site

### ISSUE THREAD

**Issue by ralanlittle** [kabanero-io/kabanero-website#40]
Alan has a new blog for the site (from Nate), I will get it in the right format check it in.  And you guys will get it on the site.

**Comment by ralanlittle** [comment]
Kevin, I have a PR opened for this Blog that Nate wrote in the Blog repo

**Comment by kSee04** [comment]
@ralanlittle Merged https://github.com/kabanero-io/blogs/pull/1

**Comment by nateziemann** [comment]
Attached is the Blog I'd like to post to promote our Announcement on IBM Developer and What's New.  This needs to be published at or after 9am ET.
As 9am ET is when the IBM Developer Blog posts and any journal articles could point to kabanero.io afer 9am ET.

**Comment by nateziemann** [comment]
[Nate's Blog for Kabanero.io.docx](https://github.com/kabanero-io/kabanero-website/files/3395078/Nate.s.Blog.for.Kabanero.io.docx)

**Comment by GeoffPirie** [comment]
+1 - Like the short summary from Nate.
