### ISSUE TITLE
Replace the Helm logo with the operator logo in all of the "kabanero collections"

### ISSUE THREAD

**Issue by ralanlittle** [kabanero-io/kabanero-website#42]
![image](https://user-images.githubusercontent.com/5471755/61143858-5be5fd80-a4a1-11e9-8c21-079d9944e1d2.png)

Replace the helm with Operator icon for all the stacks (all of them are changed).

**Comment by ralanlittle** [comment]
![Operator-85x85](https://user-images.githubusercontent.com/5471755/61145266-fac02900-a4a4-11e9-8d6a-97cae02fe847.png)
![Operator-100x100](https://user-images.githubusercontent.com/5471755/61145279-03186400-a4a5-11e9-8eb3-596fdc23d4a2.png)

**Comment by kSee04** [comment]
@ralanlittle the `Application Stacks` section was removed in https://github.com/kabanero-io/kabanero-website/pull/32 - is this issue still valid?
