### ISSUE TITLE
The contribution page on the website needs to contain the more details on what contributions look like

### ISSUE THREAD

**Issue by ralanlittle** [kabanero-io/kabanero-website#60]
We need to layout how the Git repo is layed out,  what are the naming conventions, where to find things in the multitude of places.

Where should you submit general issues,  how will the PR process work.

**Comment by alohr51** [comment]
@ralanlittle anything additional you wanted added? 

We will add more info too like a dedicated section how to setup the website locally, code styles we use, etc...
