### ISSUE TITLE
Add Updated Getting Started section

### ISSUE THREAD

**Issue by alohr51** [kabanero-io/kabanero-website#88]
Design will provide a new getting started section / experience for the end user

Some design talk for this is being done in https://github.com/kabanero-io/kabanero-foundation/issues/27

**Comment by mdenby** [comment]
We met with Nate on Friday the 16th about Getting Started/Docs/Homepage. I've updated the prototype and created this Box Note for @ziemann and @bschrammIBM  to collaborate on for copy. I also met with Carrie (visual design) so she can start looking at Getting Started.

https://ibm.ent.box.com/notes/510169547994

Prototype: https://ibm.invisionapp.com/share/GNNZ58FRJ7M

**Comment by mdenby** [comment]
[Kabanero website Home.zip](https://github.com/kabanero-io/kabanero-website/files/3546934/Kabanero.website.Home.zip)

**Comment by mdenby** [comment]
Here are the rest of the pages. We can ignore the Guides sections of the Getting Started pages for now.

[Archive.zip](https://github.com/kabanero-io/kabanero-website/files/3547073/Archive.zip)

**Comment by alohr51** [comment]
@ralanlittle is going to take a crack at updating the box note. All we're missing is good/correct content before we publish this new experience. Then we also need approval from @nateziemann

**Comment by marikaj123** [comment]
@alohr51 - What are the required next steps before it can get closed?

**Comment by alohr51** [comment]
I would actually say this can be closed, all the code is there for the Getting Started section, but the content is not so its not published. The Epic for the content is https://github.com/kabanero-io/kabanero-website/issues/188 which is the next step for releasing the getting started experience.
