### ISSUE TITLE
Generic mobile improvements

### ISSUE THREAD

**Issue by alohr51** [kabanero-io/kabanero-website#97]
The site looks "okay" in mobile due to using Bootstrap's reactive properties. We need to make it look better. Things that will be improved with this issue:

1. The Burger icon should be white and possibly moved to the upper left corner (not sure what the best mobile standard is for that)
   1. The menu that pops up from click on the burger menu should not take up the whole page (maybe just a column on the left) and not be a gradient color. Maybe either the Kabanero color or a light black color with white text

1. When you click on the burger icon there’s a random grey line and the logo is slightly cut off

![Screenshot 2019-08-02 at 17.47.05.png](https://images.zenhubusercontent.com/58debe7251aa2c30577a1512/b10afbda-e3e6-45d5-a411-65889c09ef05)

1. The `Kabanero Application Development and Deployment Lifecyle` section boxes do not scale well. The boxes are squashed as is the content is reveals. This might deserve to be its own piece of work / issue. Try it out and if its hard / needs a redesign then open a new issue.

1. The `Try it` page doesn’t scroll smoothly its very choppy. (on mobile safari iOS)

**Comment by DunnCoding** [comment]
@Bazif-Khan is looking into fixing the issue with the navbar section on mobile, and I believe tablet as well. 

The `Kabanero Application Development and Deployment Lifecyle` will need to be its own issue. In the current form I can't see it working well on mobile, so it will need a redesign. A short term solution could be to hide it on mobile but long term we should consider a better solution. 

Also I can't assign @Bazif-Khan to this issue, nor can he assign himself.
