### ISSUE TITLE
Add a "What's New" modal on the site

### ISSUE THREAD

**Issue by alohr51** [kabanero-io/kabanero-website#98]
With each release we're going to be shipping a what's new text, the text will be shown on a modal.

The text may come from the docs repo or just a html file in the website repo we need to discuss.

We still need some talk about when the modal will pop up (on visit to site, on button click, etc...) We want to be non-intrusive with the pop up and and not-in-your-face.

Discussion points

1. Who writes the whats new text each release?
1. Where info will be placed?
1. How will the modal be opened?

**Comment by alohr51** [comment]
we decided to go with a flow that has a button in the upper right with a red exclamation point that when clicked opens the modal with the "What's New?" text.

Flow is as follows:
There are 2 local storage variables in use: `didOpenWhatsNew` and `whatsNewVersion`

1. On page load js will check the "what's new" text and parse out the version number

1. js will check the version number against local storage `whatsNewVersion` variable.
   1. If they are the same 
      1. Check `didOpenWhatsNew` value
         1. If true, do nothing.
         1. If false, add red exclamation point next to whats new icon

   1. If they are different
      1. Add the red exclamation point next to the "what's new" icon.
      1. Update the `whatsNewVersion` local storage value to the new version number.
      1. Update the `didOpenWhatsNew` local storage value to `false`

1. User clicks on what's new icon a modal pops up with text from the what's new doc (from the docs repository)
   1. js sets local storage `didOpenWhatsNew` value to `true`

**Comment by mdenby** [comment]
@kidus60 @alohr51 Let's have a slide down from the top of the page with a 'x' to close it. When it closes have it slide up off of the page. The text can be a short description about what's new. Learn more can open the modal with details...though I wonder if we have a page with a Kabanero change log we can direct them to?

![Modal](https://user-images.githubusercontent.com/26823018/62985529-b9090200-be05-11e9-98b5-fc93de89eb80.jpg)
